#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-cvar
Version  : 0.5
Release  : 5
URL      : https://cran.r-project.org/src/contrib/cvar_0.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/cvar_0.5.tar.gz
Summary  : Compute Expected Shortfall and Value at Risk for Continuous
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-Rdpack
Requires: R-gbutils
BuildRequires : R-PerformanceAnalytics
BuildRequires : R-Rdpack
BuildRequires : R-fGarch
BuildRequires : R-gbutils
BuildRequires : buildreq-R

%description
quantile function, distribution function, random number generator or
    probability density function.  ES is also known as Conditional Value at
    Risk (CVaR). Virtually any continuous distribution can be specified.
    The functions are vectorized over the arguments. The computations are
    done directly from the definitions, see e.g. Acerbi and Tasche (2002)

%prep
%setup -q -n cvar
cd %{_builddir}/cvar

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667874484

%install
export SOURCE_DATE_EPOCH=1667874484
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/cvar/DESCRIPTION
/usr/lib64/R/library/cvar/INDEX
/usr/lib64/R/library/cvar/Meta/Rd.rds
/usr/lib64/R/library/cvar/Meta/features.rds
/usr/lib64/R/library/cvar/Meta/hsearch.rds
/usr/lib64/R/library/cvar/Meta/links.rds
/usr/lib64/R/library/cvar/Meta/nsInfo.rds
/usr/lib64/R/library/cvar/Meta/package.rds
/usr/lib64/R/library/cvar/Meta/vignette.rds
/usr/lib64/R/library/cvar/NAMESPACE
/usr/lib64/R/library/cvar/NEWS.md
/usr/lib64/R/library/cvar/R/cvar
/usr/lib64/R/library/cvar/R/cvar.rdb
/usr/lib64/R/library/cvar/R/cvar.rdx
/usr/lib64/R/library/cvar/REFERENCES.bib
/usr/lib64/R/library/cvar/doc/Guide_cvar.R
/usr/lib64/R/library/cvar/doc/Guide_cvar.Rnw
/usr/lib64/R/library/cvar/doc/Guide_cvar.pdf
/usr/lib64/R/library/cvar/doc/index.html
/usr/lib64/R/library/cvar/help/AnIndex
/usr/lib64/R/library/cvar/help/aliases.rds
/usr/lib64/R/library/cvar/help/cvar.rdb
/usr/lib64/R/library/cvar/help/cvar.rdx
/usr/lib64/R/library/cvar/help/paths.rds
/usr/lib64/R/library/cvar/html/00Index.html
/usr/lib64/R/library/cvar/html/R.css
/usr/lib64/R/library/cvar/tests/testthat.R
/usr/lib64/R/library/cvar/tests/testthat/a.RDS
/usr/lib64/R/library/cvar/tests/testthat/a_before_6.0.RDS
/usr/lib64/R/library/cvar/tests/testthat/a_pred.RDS
/usr/lib64/R/library/cvar/tests/testthat/a_pred_before_6.0.RDS
/usr/lib64/R/library/cvar/tests/testthat/test-VaR.R
/usr/lib64/R/library/cvar/tests/testthat/test-garch.R
